//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace School_Sys_Application.Teacher
{


    public partial class stAttendanceDetails
    {

        /// <summary>
        /// MarkDetail1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::School_Sys_Application.StudentAttendanceUC MarkDetail1;
    }
}
